#!/usr/bin/env sh
# raid-provision.sh — install and provision a local Raid deployment.
#
# Safer defaults: everything under /var/lib/offense/raid, data files removed
# before a fresh provision, policy activated at boot, and a verifiable demo
# at the end. Idempotent enough to re-run after failures; never run with
# sudo unless the UID/SOCKET paths require it.
#
# Usage:
#   RAID_REPO=/path/to/raid ./raid-provision.sh
#   RAID_SOCKET=/custom/raid.sock RAID_DB=/custom/raid.db RAID_POLICY=... ./raid-provision.sh
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="${RAID_REPO:-$(dirname "$HERE")}"
PREFIX="${RAID_PREFIX:-/var/lib/offense/raid}"
# Unprivileged fallback: user state dir when the system prefix is not writable.
if ! mkdir -p "$PREFIX" 2>/dev/null; then
  PREFIX="${RAID_PREFIX:-$HOME/.local/state/offense/raid}"
fi
SOCK="${RAID_SOCKET:-$PREFIX/raid.sock}"
DB="${RAID_DB:-$PREFIX/raid.db}"
KEY="${RAID_KEY:-$PREFIX/ed25519.seed}"
POLICY="${RAID_POLICY:-$REPO/examples/policies/surge-default.yaml}"
APPROVER_SUBJECT="${RAID_APPROVER_SUBJECT:-$(id -un)}"
APPROVER="${RAID_APPROVER:-$APPROVER_SUBJECT:maintainers,admins}"
UID_LIST="${RAID_UID:-0 $(id -u)}"

log() { printf '\n== %s\n' "$*"; }

require() {
  command -v "$1" >/dev/null 2>&1 || { echo "missing: $1 (install it first)" >&2; exit 1; }
}

require go
require curl

log "1/4 build (single binary: raid + raidd)"
cd "$REPO"
env -u GOMOD go build -o raid ./main
[ -e raidd ] || ln -sf raid raidd

log "2/4 prepare deployment directory"
mkdir -p "$PREFIX"
rm -f "$SOCK" "${DB}"* "$KEY" 2>/dev/null || true
# key seed is generated by the daemon on first boot; perms kept tight.

log "3/4 boot raidd on $SOCK with policy $POLICY"
uid_args=""
for u in $UID_LIST; do uid_args="$uid_args --uid $u"; done
nohup "$REPO/raidd" \
  --socket "$SOCK" \
  --db "$DB" \
  --policy "$POLICY" \
  --key "$KEY" \
  $uid_args \
  --approver "$APPROVER" \
  > "$PREFIX/raidd.log" 2>&1 &

log "4/4 wait for readiness"
for _ in $(seq 1 50); do
  if [ -S "$SOCK" ] && curl -s --max-time 1 --unix-socket "$SOCK" http://localhost/v1/policies/active >/dev/null 2>&1; then
    break
  fi
  sleep 0.2
done

export RAID_SOCKET="$SOCK"
export RAID_APPROVER="$APPROVER_SUBJECT"

log "sanity: raid doctor"
"$REPO/raid" doctor

log "demo: reader (allow, no prompt)"
"$REPO/raid" decision eval --request "$REPO/examples/surge/reader-list.json" | head -c 160; echo

log "demo: production label write (require_approval)"
RESP="$("$REPO/raid" decision eval --request "$REPO/examples/surge/label-write-prod.json")"
echo "$RESP" | head -c 200; echo
APR="$(echo "$RESP" | sed -n 's/.*"approval":{"id":"\([a-z0-9_]*\)".*/\1/p')"

log "demo: approve once (expect_approval at version 0)"
"$REPO/raid" approval approve "$APR" --expected-version 0 | sed 's/,"signature":"[^"]*"/,"signature":"<sig>"/' | head -c 240; echo

log "demo: deterministic deny (never prompts)"
"$REPO/raid" decision eval --request "$REPO/examples/surge/delete-repo.json" | head -c 160; echo

log "provisioned. Interact:"
printf '  export RAID_SOCKET=%s\n' "$SOCK"
printf '  %s/raid approval list\n' "$REPO"
printf '  %s/raid approve            # interactive TUI (requires a TTY)\n' "$REPO"